export default {
  primary:       '#534AB7',
  primaryLight:  '#EEEDFE',
  primaryMid:    '#AFA9EC',
  primaryDark:   '#3C3489',
  teal:          '#1D9E75',
  success:       '#1D9E75',
  tealBg:        '#E1F5EE',
  tealDark:      '#085041',
  amber:         '#BA7517',
  amberBg:       '#FAEEDA',
  amberDark:     '#633806',
  danger:        '#A32D2D',
  dangerBg:      '#FCEBEB',
  surface:       '#F8F8F8',
  white:         '#FFFFFF',
  border:        '#E0E0E0',
  borderLight:   '#F0F0F0',
  textPrimary:   '#1A1A1A',
  textSecondary: '#6B6B6B',
  textMuted:     '#A0A0A0',
};
